# This file was generated by GoReleaser. DO NOT EDIT.
cask "konfi" do
  version "0.32.4"

  on_macos do
    on_intel do
      sha256 "15b0938542e5678a0d4148c6bbe63cc960a7afa2b14e3a0cb03f732cdfb737d7"
      url "https://github.com/getkonfi/konfi/releases/download/v#{version}/konfi_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/getkonfi/konfi/"
    end
    on_arm do
      sha256 "de1bfcb9a27ce1b76e800e938ecad0ac08307a448891d486db060cdb5e14ee1d"
      url "https://github.com/getkonfi/konfi/releases/download/v#{version}/konfi_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/getkonfi/konfi/"
    end
  end

  on_linux do
    on_intel do
      sha256 "45add9c14d63f00d9cd1d5e40dbcac3d21f024ebd7527267766dcc99885632be"
      url "https://github.com/getkonfi/konfi/releases/download/v#{version}/konfi_#{version}_linux_amd64.tar.gz",
        verified: "github.com/getkonfi/konfi/"
    end
    on_arm do
      sha256 "42d851f98f95827645a7dfa888995fff33e999912dc8a78d73873317f43d7d9e"
      url "https://github.com/getkonfi/konfi/releases/download/v#{version}/konfi_#{version}_linux_arm64.tar.gz",
        verified: "github.com/getkonfi/konfi/"
    end
  end

  name "konfi"
  desc "TUI for editing dotfiles with cross-app theme sync."
  homepage "https://github.com/getkonfi/konfi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "konfi"

  # No zap stanza required

end
