# This file was generated by GoReleaser. DO NOT EDIT.
cask "konfi" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "067cfbd879967a96af6d41a21ce0259a6abb724fb5213e1f2a1848758517a978"
      url "https://github.com/getkonfi/konfi/releases/download/v#{version}/konfi_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/getkonfi/konfi/"
    end
    on_arm do
      sha256 "cefaad61230d72b1deb71e5a949e154fe0a4f9d6d7b2ec3ba9af77dea53c5a57"
      url "https://github.com/getkonfi/konfi/releases/download/v#{version}/konfi_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/getkonfi/konfi/"
    end
  end

  on_linux do
    on_intel do
      sha256 "b7d6825d1e599fecff6c32e5f8e6f71a0a3bca9d60ad27c71687ce670cb60649"
      url "https://github.com/getkonfi/konfi/releases/download/v#{version}/konfi_#{version}_linux_amd64.tar.gz",
        verified: "github.com/getkonfi/konfi/"
    end
    on_arm do
      sha256 "498c1b00f5d7857933850b1e54f5d6d6730ed1e3caeb2da07b0cf11776911c71"
      url "https://github.com/getkonfi/konfi/releases/download/v#{version}/konfi_#{version}_linux_arm64.tar.gz",
        verified: "github.com/getkonfi/konfi/"
    end
  end

  name "konfi"
  desc "TUI for editing dotfiles with cross-app theme sync."
  homepage "https://github.com/getkonfi/konfi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "konfi"

  # No zap stanza required

end
